CREATE TABLE user (

   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL
);

CREATE TABLE question (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   content VARCHAR(255) NOT NULL,
   user_id BIGINT,
   FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE answer (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   content TEXT NOT NULL,
   question_id BIGINT,
   user_id BIGINT,
   FOREIGN KEY (question_id) REFERENCES question(id),
   FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE comment (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   content TEXT NOT NULL,
   answer_id BIGINT,
   user_id BIGINT,
   FOREIGN KEY (answer_id) REFERENCES answer(id),
   FOREIGN KEY (user_id) REFERENCES user(id)
);
